services:
  postgres:
    image: postgres:17

    container_name: lifetracker-postgres

    environment:
      POSTGRES_DB: lifetracker
      POSTGRES_USER: lifetracker
      POSTGRES_PASSWORD: lifetracker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: