spring.application.name=lifetracker

spring.datasource.url=jdbc:postgresql://localhost:5432/lifetracker
spring.datasource.username=lifetracker
spring.datasource.password=lifetracker

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true